[package]
name = "lambda"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
axum = "0.8.8"
bb8 = "0.9.1"
dotenvy = "0.15.7"
oauth2 = "5.0.0"
redis = { version = "1.0.3", features = ["bb8", "tokio-rustls-comp"] }
tokio = { version = "1.49.0", features = ["macros", "rt-multi-thread"] }
